baseURL = 'https://investmuse.io/blog'
languageCode = 'en-us'
title = 'InvestMuse Blog'
theme = 'clarity'

[params]
  brand = "InvestMuse"
  introDescription = "Professional investment analysis insights, tips, and market intelligence"
  logo = "/images/logo.png"

[params]
  customCSS = ["css/_custom.css"]
  
[menu]
  [[menu.main]]
    name = "InvestMuse App"
    url = "https://investmuse.io"
    weight = 1
  [[menu.main]]  
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.asciidocExt]
    [markup.asciidocExt.attributes]
