baseURL = 'https://investmuse.io/blog'
languageCode = 'en-us'
title = 'InvestMuse Blog'
theme = 'clarity'

[params]
  brand = "InvestMuse"
  introDescription = "Professional investment analysis insights, tips, and market intelligence"
  logo = "/images/logo.png"
  
[menu]
  [[menu.main]]
    name = "InvestMuse App"
    url = "https://investmuse.io"
    weight = 1
  [[menu.main]]  
    name = "About"
    url = "/about/"
    weight = 2
